name: 2020.2.18 Revoke Token 
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: RevokeToken
        cxToken: ${{ secrets.CX_TOKEN }}
        cxVersion: "2020.2.18"
        cxLog: log.log
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: log.log
        path: log.log
