name: 2020.2.18 SCA Scan
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxAction: ScaScan
        cxScaAccount: ${{ secrets.CX_SCA_ACCOUNT }}
        cxScaUsername: ${{ secrets.CX_SCA_USERNAME }}
        cxScaPassword: ${{ secrets.CX_SCA_PASSWORD }}
        cxScaPathExclude: coverage,images
        cxExecutePackageDependency: true
        cxVersion: "2020.2.18"
        cxLog: log.log
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log
