name: 2020.1.12 Generate Token Wrong Credentials
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: ./
      with:
        cxServer: ${{ secrets.CX_SERVER }}
        cxAction: GenerateToken
        cxUsername: ${{ secrets.CX_EMAIL }}
        cxPassword: "123456"
        cxSkipIfFail: true
        cxVersion: "2020.2.11"
        cxLog: log.log
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: log.log
        path: log.log
